name: CI

on:
  workflow_dispatch:
  push:
    paths:
    - '**'
    - '!**.md'
    - '!doc/**'
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.0.2
